### ISSUE TITLE
Add option to trigger pool prefaulting

### ISSUE THREAD

**Issue by igchor** [pmem/pmemstream#179]
# FEAT: Add option to trigger pool prefaulting

## Rationale

Right now, we are always clearing the unused part of the region on restart (to make sure that we don't have any trash which could be later interpreted as data). Because of this, all pages to which we will later write (inside append) are already prefaulted.

Once we get rid of clearing the regions, appends might trigger page fault. To get valid benchmarking results we should add option to force prefault at open/create time.

## Description

Similar to: https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_ctl_get.3/

## API Changes

None. Add ENV var to trigger page faults.

**Comment by lukaszstolarczuk** [comment]
Done in #263
