### ISSUE TITLE
FEAT: Support for multithreaded region allocation

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmemstream#181]
# FEAT: Support for multithreading in region allocator

## Rationale
Developer have to keep thread-safety, safer is move this responsibility to the library.

## Description
For now, allocator design doesn't support multithreading for adding, removing. Using iterators during allocate/free causes undefined behavior.
Affected API functions:
`pmemstream_region_allocate`
`pmemstream_region_free`
and all region iteration functions.

## API Changes
There is no need to change API.

## Implementation details
N/A

**Comment by lukaszstolarczuk** [comment]
covered by https://github.com/pmem/pmemstream/issues/74
