### ISSUE TITLE
Arguments refactor

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmemstream#36]
Simplify argument passed to functions.
1. `pmemstream_span_create_empty(stream, &stream->data->spans[0], stream->usable_size - metadata_size);`
should be changed to:
`pmemstream_span_create_empty(stream, stream->usable_size - metadata_size);`
2. Change `&span[0]` -> `span`

**Comment by igchor** [comment]
@KFilipek why do you want to remove span parameter from pmemstream_span_create_empty?

**Comment by igchor** [comment]
Already fixed I believe
