### ISSUE TITLE
FEAT: Timestamps and async API

### ISSUE THREAD

**Issue by igchor** [pmem/pmemstream#78]
# FEAT: Timestamps and async API

## Rationale

- Will be used to ensure data consistency instead of popcount: offloads some of the work to background thread to speed up user threads
- Foundation for Transactions (#77)

## Description

- Each entry stores timestamp which describes when the entry was created (all entries created in one tx have the same timestamp)
- On pmem, we store the latest timestamp, which is known to be persistent (all entries with timestamps less or equal, are persisted). 
- On DRAM we store the highest timestamp, which is known to be committed.

### Timestamps generation and data persistence

- Data is stored using NONTEMPORAL stores (in pmemstream_append)
- Timestamp is generated by incrementing a global, runtime counter (either in pmemstream_append or on transaction commit) and storing this timestamp inside entry.
- Persisted timestamp is updated and persisted by a separate async function that scans in-progress regions. This function can be run in arbitrary thread: https://github.com/pmem/pmemstream/blob/master/examples/04_basic_async/main.cpp

Example of pmemstream with 3 entries:
![image](https://user-images.githubusercontent.com/29300828/149767683-2636f1f5-1e32-483c-b76d-fd2341007691.png)

**Comment by lukaszstolarczuk** [comment]
Done
