### ISSUE TITLE
Assertion fault in span_get_region_runtime

### ISSUE THREAD

**Issue by Karolina002** [pmem/pmemstream#99]
# ISSUE: 
assertion fault in span_get_region_runtime when passing invalid region offset

## The bug reproduction:

	struct pmemstream_region region = {.offset = ALIGN_DOWN(UINT64_MAX, sizeof(span_bytes))};
	ret = pmemstream_reserve(stream, region, NULL, sizeof(data), &entry, &data_address);

## How often bug is revealed:
always

##  Actual behavior:

     __GI___assert_fail (assertion=0x7ffff7f226f0 "span_get_type(span) == SPAN_REGION", 
    span_get_region_runtime () at /PMDK/pmemstream/src/span.c:121
    pmemstream_reserve () at /PMDK/pmemstream/src/libpmemstream.c:166
    invalid_region_test () at /PMDK/pmemstream/tests/api_c/reserve_and_publish.c:85
    main () at /PMDK/pmemstream/tests/api_c/reserve_and_publish.c:189

**Comment by lukaszstolarczuk** [comment]
@Karolina002, please re-check this issue, I'm not sure if this is still an issue (after some recent @igchor's change). Perhaps the error changed, but at least we're no longer getting an assert, I believe.

**Comment by Karolina002** [comment]
No longer an issue after code changes.
